### ISSUE TITLE
Allow setting custom URLs for Octobox inboxes

### ISSUE THREAD

**Issue by pradyunsg** [tfrommen/octobox-web-extension#2]
This would allow for me to point it to my own deployment of Octobox (since Octobox.io disables some features).

**Comment by tfrommen** [comment]
Oh, that's a great idea. Thanks for the suggestion.

**Comment by tfrommen** [comment]
Implemented in https://github.com/tfrommen/octobox-web-extension/commit/ee7514a748c248985b8033e94f13b692aace2693.

**Comment by tfrommen** [comment]
Maybe I should mention that I did not make any changes to also include the _Back to GitHub_ links (as well as the icon in the top bar) to a self-hosted Octobox. Reason is that I could only do this by targeting **all URLs**, which is not something I would like to do, and even then you could have somehow _changed_ the HTML of your Octobox, so I might not be able to easily inject the link properly anyway.
